### ISSUE TITLE
🛡 Primer Trimestre

### ISSUE THREAD

**Issue by Rayelus5** [Rayelus5/DAW-javacourse#5]
### 🔻 Contenidos:
- Damos por primera vez los bucles
- Primer bucle "**while**"
- Sintaxis y lógica del bucle "**while**"

<br>

### 🔻 Prácticas:
- Ejercicios 1, 2, 3, 4 de la  #4 

<br>

### 🔻 Tarea:
- [ ] Actividades 1 - 4 de la  #4

**Comment by Rayelus5** [comment]
## Clase Programación - (8/10/24)

### 🔻 Contenidos:
- Damos los siguientes bucles
- "**for**" y "**do ... while**"
- Sintaxis y lógica del bucle "**for**" y  "**do ... while**"

<br>

### 🔻 Prácticas:
- Ejercicios 5 y 6 de la  #4 

<br>

### 🔻 Tarea:
- [ ] Actividades 1 - 7 de la  #4

**Comment by Rayelus5** [comment]
## Clase Programación - (9/10/24)

### 🔻 Contenidos:
- Hacemos ejercicios en clase de la #4 
- Utilizamos los bucles dados
- El Viernes el profesor no adelantará materia (huelga)

<br>

### 🔻 Prácticas:
- Ejercicios 6 - 12 de la  #4 

<br>

### 🔻 Tarea:
- [ ] Actividades de la  #4

**Comment by Rayelus5** [comment]
## Clase Programación - (11/10/24)

### 🔻 Contenidos:
- Examen de prueba 2022

<br>

### 🔻 Prácticas:
- Examen de prueba 2022
- Instalación de Auto Hot Key 

<br>

### 🔻 Tarea:
- [ ] Actividades de la  #4 
- [ ] Revisar solución del examen

**Comment by Rayelus5** [comment]
## Clase Programación - (16/10/24)

### 🔻 Contenidos:
- Exámenes anteriores (Desde 2017 hasta 2023)
- Ejercicios tipo examen (4 Ejercicios)

<br>

### 🔻 Prácticas:
- Ejercicios tipo examen

<br>

### 🔻 Tarea:
- [ ] Actividades de la  #4 
- [ ] Ejercicios tipo examen
- [ ] Exámenes de años anteriores

**Comment by Rayelus5** [comment]
## Clase Programación - (22/10/24)

### 🔻 Contenidos:
- Exámenes anteriores (Desde 2017 hasta 2023)
- Ejercicios tipo examen (4 Ejercicios) RESUELTOS YA
- Examen 2021-2022

<br>

### 🔻 Prácticas:
- Ejercicios tipo examen

<br>

### 🔻 Tarea:
- [ ] Actividades de la  #4 
- [x] Ejercicios tipo examen
- [ ] Exámenes de años anteriores
- [x] Examen año 2021-2022
